general {
    immediate_render = true
    hide_cursor = true
}

background {
    monitor =
    color = rgba(8,8,12,1.0)
}

image {
    monitor =
    path = /home/basant/Pictures/wallhaven-1qrwv9.png

    size = 1100
    rounding = 0
    border_size = -10

    position = 0, 0
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 1000, 500
    outline_thickness = 0
    rounding = 0

    dots_center = true
    dots_text_format = [力火影斬剣空龍闇神心道武魂夢月天風雷]
    dots_text_change = false

    fade_on_empty = true
    hide_input = false

    font_family = Noto Sans CJK JP
    font_size = 400
    font_color = rgba(255,255,255,0.92)

    inner_color = rgba(0,0,0,0.0)
    outer_color = rgba(0,0,0,0.0)
    check_color = rgba(0,0,0,0.0)
    fail_color = rgba(0,0,0,0.0)

    placeholder_text =

    position = -400, 40
    halign = center
    valign = bottom
}

label {
    monitor =
    text = $TIME
    font_family = Noto Sans
    font_size = 130
    color = rgba(180,220,180,0.85)

    position = 200, 80
    halign = left
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date '+%Y年%m月%d日'
    font_family = Noto Sans CJK JP
    font_size = 24
    color = rgba(180,220,180,0.45)

    position = 210, 175
    halign = left
    valign = center
}
